#!/usr/bin/env python3
"""refute.py: try to kill a finding before it gets submitted.

The second stage of the pipeline, between "the tool said so" and "a human took
it somewhere".

WHY. The working rule is to try proving a finding does not exist before writing
a pull request. Until now that was done by hand for every finding, and it is the
most expensive part of the work, more expensive than waiting for a merge. On the
documentation species the manual cull reached 101 false out of 103 in Boost.Beast
and 25 out of 25 in asio.

WHY A SEPARATE TOOL RATHER THAN A PART OF EACH DETECTOR. Because these rules had
already been written nine times in a row, once per detector: generated file,
archived documentation, a version caveat nearby, a coordinate pointing at a
comment. Nine copies of one piece of knowledge drift apart, which had already
happened once with the skip list and once with the hardness flag.

WHAT IT DOES. Takes the JSON findings of ANY tool in the kit, pulls `file:line`
coordinates out of them (every tool has them, under different key names) and runs
independent refutations against each finding. Every refutation answers one
question and is able to say "I do not know".

THE REFUTATIONS, every one of them taken from a live case:

  the coordinate does not exist: no such file, or the line is past the end. The
      finding is stale or the tool lied. Checked first, since it invalidates the
      rest;
  the file is generated: `Code generated ... DO NOT EDIT`. Carrying a patch
      there is pointless, the generator is what needs fixing (otelcol, 12
      candidates);
  an archived path: `versioned_docs/`, `docs/v3.5/`, `postmortems/`,
      `READMEv2.md`. Stale content is required to stay there (etcd);
  a caveat nearby: "for versions v2.38 and below", "legacy", "no longer". That is
      correct documentation (Prometheus);
  test data: `testdata/`, `fixtures/`, `examples/`. Anything at all may sit there
      on purpose;
  the line is commented out: the coordinate points at a comment inside a code
      file. Often means the place is already switched off;
  the findings cluster: many findings in one file are one trouble rather than N.
      A kit-wide rule derived three times on different tools.

WHAT THE REFUTER DOES NOT DO:
  - it does not decide for a human. It says "here is a reason to consider this
    false", and agreeing is up to the reader;
  - it does not check the substance of a finding. It knows the context rather
    than the subject: whether a field really disappeared, whether a link really
    is dead, it does not judge;
  - it stays quiet where it does not know, and that gets printed as a number.

KNOWN BLIND SPOTS:
  - **project conventions that live outside the tree.** When "this is how we do
    it here" lives in maintainers' heads rather than in files, there is nothing
    to refute against;
  - **findings without coordinates.** It extracts `file:line` by the shape of the
    value; whatever it fails to parse gets skipped and counted out loud;
  - **the substance of a finding.** Knowing the context and not the subject, it
    can both leave a false finding alive and, worse, kill a real one. The
    ecologits case: bare version numbers in `pyproject.toml` were taken for a
    caveat and a live finding died. Since then every suppression rule is narrow
    and prints its own reason.

Run:
  python3 refute.py --findings out.json
  python3 refute.py --findings out.json --root ~/Projects/oss/etcd
  python3 refute.py --findings out.json --survivors ok.json

Tests: test_refute.py next to this file.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field as dc_field
from typing import Any, Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import common  # noqa: E402
import stamp  # noqa: E402

COORD = re.compile(r"^(?P<path>[^\s:][^:]*?):(?P<line>\d+)$")

GENERATED = re.compile(
    r"^\s*(?://|#|--|<!--|/\*|\*)?\s*(?:Code generated|@generated|Autogenerated|"
    r"AUTO-GENERATED|Generated by|DO NOT EDIT)", re.M | re.I
)
ARCHIVED = re.compile(
    r"(?:^|/)(?:versioned_docs|v\d+(?:\.\d+)*|_archive|archive|history|"
    r"postmortems?|deprecated|legacy|old|CHANGELOG)(?:/|$)"
    r"|(?:^|/)[A-Za-z_-]*v\d+\.[a-z]+$",
    re.I,
)
FIXTURES = re.compile(r"(?:^|/)(?:testdata|fixtures?|examples?|samples?|mocks?|__snapshots__)(?:/|$)", re.I)
# A caveat is LANGUAGE. A bare `3.11` nearby means nothing on its own: the
# classifier list in pyproject.toml consists of version numbers entirely, and
# under the old rule the refuter killed a real finding in ecologits. Killing a
# real finding is worse than letting a false one through.
QUALIFIED = re.compile(
    r"\bversions?\s+v?\d+[\d.]*\s+(?:and\s+)?(?:below|earlier|older|prior|before)\b|"
    r"\b(?:before|prior\s+to|up\s+to|until)\s+v?\d+[\d.]*\b|"
    r"\b(?:no\s+longer|legacy|obsolete|historical|deprecated|was\s+removed|"
    r"has\s+been\s+removed|in\s+older\s+versions)\b|"
    r"\bnot supported (?:any more|anymore)\b",
    re.I,
)
CODE_EXT = (".go", ".c", ".h", ".cc", ".cpp", ".hpp", ".rs", ".py", ".java", ".js", ".ts", ".rb", ".sh")
COMMENT_LINE = re.compile(r"^\s*(?://|#|--|;|/\*|\*|<!--)")

CLUSTER_MIN = 5  # this many findings in one file already read as one trouble


@dataclass
class Verdict:
    index: int
    subject: str
    coords: List[Tuple[str, int]]
    killed_by: List[str] = dc_field(default_factory=list)
    unknown: List[str] = dc_field(default_factory=list)

    @property
    def survives(self) -> bool:
        return not self.killed_by


@dataclass
class Report:
    total: int = 0
    no_coords: List[str] = dc_field(default_factory=list)
    verdicts: List[Verdict] = dc_field(default_factory=list)
    clusters: List[str] = dc_field(default_factory=list)
    lessons_loaded: int = 0

    @property
    def survivors(self) -> List[Verdict]:
        return [v for v in self.verdicts if v.survives]

    @property
    def killed(self) -> List[Verdict]:
        return [v for v in self.verdicts if not v.survives]


# --------------------------------------------------------------------------


LINE_KEYS = ("line", "lineno", "line_no", "row")
PATH_KEYS = ("file", "path", "filename", "where", "source")


def split_coord(node: dict) -> List[Tuple[str, int]]:
    """A coordinate split across two fields, `file` and `line` separately.

    The `path:line` form was understood from the start, the split one was not,
    and on docdrift findings the refuter honestly printed "no coordinates" for
    all nineteen. The mistake was silent: it only made the report look tidier.
    Same family as the dropped `.github` directory.
    """
    line = next((node[k] for k in LINE_KEYS
                 if isinstance(node.get(k), int) and not isinstance(node.get(k), bool)), None)
    if line is None or line <= 0:
        return []
    for k in PATH_KEYS:
        v = node.get(k)
        if isinstance(v, str) and v and ("/" in v or "." in os.path.basename(v)):
            return [(v, line)]
    return []


def coords_of(finding: Any) -> List[Tuple[str, int]]:
    """Every `file:line` coordinate present in a finding.

    Field names differ across the tools (`copy`, `where`, `field_ref`, `a_ref`,
    `original` and so on), so the search goes by the shape of the value rather
    than the key name. A new tool then gets picked up with no edit here.
    """
    out: List[Tuple[str, int]] = []

    def walk(node: Any) -> None:
        if isinstance(node, str):
            m = COORD.match(node.strip())
            if m:
                out.append((m.group("path"), int(m.group("line"))))
        elif isinstance(node, dict):
            out.extend(split_coord(node))
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(finding)
    seen = set()
    uniq = []
    for c in out:
        if c not in seen:
            seen.add(c)
            uniq.append(c)
    return uniq


def subject_of(finding: Any, index: int) -> str:
    if isinstance(finding, dict):
        for key in ("subject", "symbol", "name", "url", "page", "a", "field",
                    "assertion", "message", "param", "func"):
            v = finding.get(key)
            if isinstance(v, str) and v:
                return v[:90]
    return f"finding #{index}"


def _resolve(root: str, path: str) -> Optional[str]:
    for cand in (path, os.path.join(root, path)):
        if os.path.isfile(cand):
            return cand
    return None


# --------------------------------------------------------------------------
# Refutations
# --------------------------------------------------------------------------


def load_lessons(path: Optional[str]) -> List[dict]:
    """Suppression rules harvested from maintainer replies.

    This closes the loop: a rejection read by a human becomes a rule, and the
    same class of finding stops reaching submission. `lessons.py` collects them;
    the wording of a rule is written by a human rather than derived by a machine.
    """
    if not path or not os.path.isfile(path):
        return []
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return []
    out = []
    for r in data if isinstance(data, list) else []:
        pat = (r or {}).get("pattern")
        if not pat:
            continue
        try:
            out.append({"rx": re.compile(pat, re.I), "why": r.get("why", ""), "src": r.get("source", "")})
        except re.error:
            continue
    return out


# Tools whose findings are ABOUT A COMMENT rather than the code beside it.
# For them a coordinate inside a comment is a hit rather than evidence against.
ABOUT_DOCS = frozenset({"docdrift", "doxdrift", "transdrift", "deaddrift", "namedrift"})
DOC_KINDS = frozenset({"param", "tparam", "A", "B"})


def about_docs(finding: Any) -> bool:
    """Whether a finding is about documentation text.

    The rule "the coordinate points at a comment rather than code" holds for
    detectors that judge code. For `doxdrift` it is lethal: it reports the line
    of a `\\param` block, a comment by construction. On Boost.Geometry that wiped
    out 24 real findings out of 24, the only case besides ecologits where the
    refuter worked against us.
    """
    if not isinstance(finding, dict):
        return False
    if finding.get("tool") in ABOUT_DOCS:
        return True
    return finding.get("kind") in DOC_KINDS and ("func" in finding or "decl" in finding)


def refute_one(root: str, path: str, line: int, lessons: Sequence[dict] = (),
               doc_finding: bool = False) -> Tuple[List[str], List[str]]:
    """Reasons to consider a finding at this coordinate false, and what is unknown."""
    killed: List[str] = []
    unknown: List[str] = []

    if ARCHIVED.search(path):
        killed.append(f"archived path: {path}")
    if FIXTURES.search(path):
        killed.append(f"test data: {path}")

    full = _resolve(root, path)
    if full is None:
        unknown.append(f"file is not there: {path}")
        return killed, unknown

    text = common.read_text(full)
    if not text:
        unknown.append(f"file is empty or unreadable: {path}")
        return killed, unknown

    lines = text.splitlines()
    if line < 1 or line > len(lines):
        killed.append(f"coordinate past the end of the file: {path}:{line} of {len(lines)} lines")
        return killed, unknown

    if GENERATED.search(text[:4000]):
        killed.append("the file is generated, the generator is what needs fixing")

    window = "\n".join(lines[max(0, line - 4) : line + 3])
    if QUALIFIED.search(window):
        killed.append("a version or history caveat sits nearby, this may be intended")

    if (not doc_finding
            and os.path.splitext(path)[1].lower() in CODE_EXT
            and COMMENT_LINE.match(lines[line - 1])):
        killed.append("the coordinate points at a comment rather than code")

    for les in lessons:
        if les["rx"].search(window) or les["rx"].search(path):
            killed.append(f"lesson from review: {les['why'][:80]} ({les['src']})")

    return killed, unknown


def analyse(findings: Sequence[Any], root: str, report: Report,
            lessons: Sequence[dict] = ()) -> None:
    report.total = len(findings)
    by_file: Dict[str, List[int]] = defaultdict(list)

    for i, f in enumerate(findings):
        coords = coords_of(f)
        v = Verdict(index=i, subject=subject_of(f, i), coords=coords)
        if not coords:
            report.no_coords.append(v.subject)
            report.verdicts.append(v)
            continue
        for path, line in coords:
            by_file[path].append(i)
        # A finding counts as refuted only when ALL of its coordinates are.
        # Comparators carry two, and if one side is alive the finding is alive.
        doc = about_docs(f)
        per_coord = [refute_one(root, p, ln, lessons, doc) for p, ln in coords]
        if all(k for k, _u in per_coord):
            for k, _u in per_coord:
                v.killed_by.extend(k)
        for _k, u in per_coord:
            v.unknown.extend(u)
        report.verdicts.append(v)

    # A pile of findings in one file is one trouble rather than N. A kit-wide
    # rule derived three times: 115 mismatches in qdrant, 17 links on one page of
    # a Chinese translation, 81 "removed flags" in sarek.
    for path, idxs in sorted(by_file.items()):
        uniq = sorted(set(idxs))
        if len(uniq) >= CLUSTER_MIN:
            report.clusters.append(f"{path}: {len(uniq)} findings, read as one trouble")


def print_report(report: Report, verbose: bool = False) -> None:
    surv, killed = report.survivors, report.killed
    if surv:
        print(f"\n=== Survived refutation ({len(surv)}) ===")
        for v in surv:
            where = ", ".join(f"{p}:{ln}" for p, ln in v.coords[:2]) or "no coordinates"
            print(f"  [{v.index:3d}] {v.subject}")
            print(f"        {where}")
            for u in v.unknown:
                print(f"        unknown: {u}")

    if killed and verbose:
        print(f"\n=== Refuted ({len(killed)}) ===")
        for v in killed:
            print(f"  [{v.index:3d}] {v.subject}")
            for k in v.killed_by:
                print(f"        {k}")

    print("\n=== Coverage ===")
    print(f"  findings submitted:     {report.total}")
    print(f"  without coordinates:    {len(report.no_coords)} (nothing to refute against)")
    print(f"  refuted:                {len(killed)}")
    print(f"  rules from review:      {report.lessons_loaded}")
    print(f"  clustered:              {len(report.clusters)}")
    for c in report.clusters[:5]:
        print(f"    {c}")
    print(common.findings_line(len(surv), 0))
    print(stamp.line(__file__, ["common.py"]))


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Try to kill a finding before it is submitted")
    ap.add_argument("--findings", required=True, help="JSON produced by any tool in the kit")
    ap.add_argument("--root", default=".", help="project root, when coordinates are relative")
    ap.add_argument("--survivors", help="write the survivors to JSON")
    ap.add_argument("--lessons", help="JSON of rules collected by lessons.py")
    ap.add_argument("--include-soft", action="store_true",
                    help="consider soft findings too")
    common.add_common_args(ap)
    args = ap.parse_args(argv)

    with open(args.findings, encoding="utf-8") as fh:
        data = json.load(fh)
    findings = data if isinstance(data, list) else data.get("findings", [])
    if not args.include_soft:
        # soft findings are already set aside as "needs reading by a human",
        # so refuting them changes nothing: they do not go to submission anyway
        findings = [f for f in findings if not isinstance(f, dict) or f.get("hard", True)]

    report = Report()
    lessons = load_lessons(args.lessons)
    report.lessons_loaded = len(lessons)
    analyse(findings, args.root, report, lessons)
    print_report(report, args.verbose)

    if args.survivors:
        with open(args.survivors, "w", encoding="utf-8") as fh:
            json.dump([findings[v.index] for v in report.survivors], fh, ensure_ascii=False, indent=1)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(
                [
                    {
                        "hard": v.survives, "index": v.index, "subject": v.subject,
                        "coords": [f"{p}:{ln}" for p, ln in v.coords],
                        "killed_by": v.killed_by, "unknown": v.unknown,
                    }
                    for v in report.verdicts
                ],
                fh, ensure_ascii=False, indent=1,
            )
    return 1 if report.survivors else 0


if __name__ == "__main__":
    sys.exit(main())
