#!/usr/bin/env python3
"""Tests for sweep.py, the run over a project.

The property the whole thing exists for: **no tool may be skipped silently**. A
run where half the checks never started has to read as "these checks do not
apply and here is why" rather than as a clean project. Same mistake as "zero
findings out of zero compared", one level up.
"""

from __future__ import annotations

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import sweep  # noqa: E402


def project(files: dict) -> str:
    root = tempfile.mkdtemp()
    for rel, body in files.items():
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(body)
    return root


def plan_for(files: dict, network: bool = False):
    root = project(files)
    s = sweep.survey(root)
    return {p.tool: p for p in sweep.build_plan(root, s, network)}, root


class TestSurvey(unittest.TestCase):
    def test_empty_project_applies_nothing(self):
        plans, _ = plan_for({"README.md": "hi\n"})
        self.assertTrue(all(not p.applies for p in plans.values()))
        for p in plans.values():
            self.assertTrue(p.reason, f"{p.tool}: no reason given")

    def test_every_plan_carries_a_reason(self):
        """A skip without a reason is indistinguishable from a breakage."""
        plans, _ = plan_for({"a.go": "package p\n" * 20, "CHANGELOG.md": "# c\n"})
        for p in plans.values():
            self.assertTrue(p.reason.strip(), p.tool)

    def test_github_workflows_are_not_skipped_as_hidden(self):
        """`.github` starts with a dot and a blanket hidden-directory mask threw
        away the CI matrices. supportdrift quietly declared projects unsuitable."""
        plans, _ = plan_for(
            {
                "pyproject.toml": '[project]\nrequires-python = ">=3.10"\n',
                ".github/workflows/ci.yml": "jobs:\n  t:\n    steps: []\n",
            }
        )
        self.assertTrue(plans["supportdrift"].applies, plans["supportdrift"].reason)

    def test_proto_and_openapi_detected(self):
        plans, _ = plan_for(
            {"api/x.proto": 'syntax = "proto3";\n', "docs/openapi.json": '{"components":{}}'}
        )
        self.assertTrue(plans["ifacedrift"].applies)
        self.assertIn("--proto-dir", plans["ifacedrift"].args[0])

    def test_generated_spec_is_warned_about(self):
        """In etcd the swagger file is generated by grpc-gateway, so no mismatch
        can exist there by construction."""
        plans, _ = plan_for(
            {"api/x.proto": 'syntax = "proto3";\n', "docs/rpc.swagger.json": "{}"}
        )
        self.assertTrue(plans["ifacedrift"].applies)
        self.assertIn("grpc-gateway", plans["ifacedrift"].reason)
        # the caveat has to be explicit, otherwise the line reads as a statement
        # coming from the project itself
        self.assertIn("our own reading", plans["ifacedrift"].reason)

    def test_locales_detected_as_pairs(self):
        plans, _ = plan_for(
            {"content/en/a.md": "# a\n", "content/ja/a.md": "# a\n", "content/zh/a.md": "# a\n"}
        )
        p = plans["transdrift"]
        self.assertTrue(p.applies)
        self.assertEqual(len(p.args), 2, "one pair per translation is expected")

    def test_locale_without_default_is_not_a_pair(self):
        plans, _ = plan_for({"content/ja/a.md": "# a\n"})
        self.assertFalse(plans["transdrift"].applies)

    def test_go_project_without_lifted_marks(self):
        plans, _ = plan_for({f"pkg/f{i}.go": "package p\n" for i in range(12)})
        self.assertTrue(plans["gitdrift"].applies)
        self.assertFalse(plans["liftdrift"].applies)
        self.assertIn("too few", plans["liftdrift"].reason)

    def test_non_go_project_says_so_for_both_go_tools(self):
        plans, _ = plan_for({"a.py": "x = 1\n"})
        for t in ("gitdrift", "liftdrift"):
            self.assertFalse(plans[t].applies)
            self.assertIn("not a Go project", plans[t].reason, t)

    def test_helm_tests_detected(self):
        plans, _ = plan_for({"chart/tests/a_test.yaml": "suite: s\ntests: []\n"})
        self.assertTrue(plans["assertdrift"].applies)


class TestNetworkGate(unittest.TestCase):
    def test_offline_by_default(self):
        """One flag for the whole kit: it used to be --offline in one place and
        --no-proof in two others."""
        plans, _ = plan_for({f"pkg/f{i}.go": "package p\n" for i in range(12)}, network=False)
        for t in ("gitdrift", "liftdrift"):
            if plans[t].applies:
                self.assertIn("--offline", plans[t].args[0], t)

    def test_network_flag_removes_the_offline_switch(self):
        plans, _ = plan_for({f"pkg/f{i}.go": "package p\n" for i in range(12)}, network=True)
        self.assertNotIn("--offline", plans["gitdrift"].args[0])


class TestSiteGate(unittest.TestCase):
    """First stage: a project we may not approach must not cost a single
    detector run."""

    def test_blocked_site_runs_no_detectors(self):
        root = project(
            {
                "AGENTS.md": "DO NOT create a Pull Request unless there is an approved Issue.\n",
                "CHANGELOG.md": "# c\n\n- Removed `--foo-bar` flag\n",
                "docs/a.md": "Use `--foo-bar`.\n",
            }
        )
        plans, results, site, _ref = sweep.sweep(root, network=False, only=None, dry=False)
        self.assertTrue(site.blocked)
        self.assertEqual(results, [], "detectors ran on a project we do not approach")

    def test_ignore_rules_lets_it_through(self):
        root = project({"AGENTS.md": "Do not open a PR unless there is an open Issue.\n", "a.md": "x\n" * 30})
        _p, results, site, _ref = sweep.sweep(root, network=False, only=None, dry=False, ignore_rules=True)
        self.assertTrue(site.blocked)
        self.assertTrue(results)


class TestRun(unittest.TestCase):
    def test_dry_run_produces_a_plan_and_no_results(self):
        root = project({"CHANGELOG.md": "# c\n\n- Removed `--foo-bar` flag\n"})
        plans, results, _site, _ref = sweep.sweep(root, network=False, only=None, dry=True)
        self.assertTrue(plans)
        self.assertEqual(results, [])

    def test_skipped_tools_appear_in_results_with_a_reason(self):
        """A skipped tool has to appear in the result rather than vanish."""
        root = project({"README.md": "hi\n" * 30})
        _plans, results, _site, _ref = sweep.sweep(root, network=False, only=None, dry=False)
        self.assertEqual(len(results), 12, "the kit has twelve detectors in the sweep and none may vanish")
        skipped = [r for r in results if not r.ran]
        self.assertTrue(skipped)
        for r in skipped:
            self.assertTrue(r.reason.strip(), r.tool)

    def test_only_filters_the_plan(self):
        root = project({"CHANGELOG.md": "# c\n"})
        plans, _r, _site, _ref = sweep.sweep(root, network=False, only=["deaddrift"], dry=True)
        self.assertEqual([p.tool for p in plans], ["deaddrift"])

    def test_registry_row_per_tool(self):
        root = project({"README.md": "hi\n" * 30})
        _plans, results, _site, _ref = sweep.sweep(root, network=False, only=["namedrift"], dry=False)
        reg = os.path.join(tempfile.mkdtemp(), "r.tsv")
        sweep.write_registry(root, results, reg)
        with open(reg, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
        self.assertEqual(lines[0].split("\t")[0], "date")
        self.assertEqual(len(lines), 2)
        self.assertIn("namedrift", lines[1])

    def test_findings_are_counted_from_json_not_parsed_from_text(self):
        """The numbers come from the tool JSON: parsing the report text would
        break on any change of wording."""
        root = project(
            {
                "CHANGELOG.md": "# c\n\n- Removed `--dump-auth` flag\n",
                "docs/a.md": "Use `--dump-auth` to see the exchange.\n",
            }
        )
        _plans, results, _site, _ref = sweep.sweep(root, network=False, only=["deaddrift"], dry=False)
        r = results[0]
        self.assertTrue(r.ran)
        self.assertEqual(r.hard, 1)
        self.assertTrue(r.fingerprint)


if __name__ == "__main__":
    unittest.main(verbosity=2)
